# Server Configuration
server.port=9998

# Key Management Configuration
keys.aes.path=classpath:keys/aes.key
keys.rsa.keystore.path=classpath:keys/keystore.p12
keys.rsa.keystore.password.path=classpath:keys/keystore.pass


# Spring Boot Actuator
management.endpoints.web.exposure.include=health,info

